In [27]:
import pandas as pd
import numpy as np
import re
import nltk

from nltk.corpus import stopwords

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [28]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [29]:
df = pd.read_csv("/content/bbc_data.csv")

In [30]:
print(df.columns)

Index(['data', 'labels'], dtype='object')

In [31]:
df.head()

                                                data         labels
0  Musicians to tackle US red tape  Musicians gro...  entertainment
1  U2s desire to be number one  U2, who have won ...  entertainment
2  Rocker Doherty in on-stage fight  Rock singer ...  entertainment
3  Snicket tops US box office chart  The film ada...  entertainment
4  Oceans Twelve raids box office  Oceans Twelve,...  entertainment

In [32]:
df.rename(columns={
    'data':'Article',
    'labels':'Category'
}, inplace=True)

In [33]:
df.head()

                                             Article       Category
0  Musicians to tackle US red tape  Musicians gro...  entertainment
1  U2s desire to be number one  U2, who have won ...  entertainment
2  Rocker Doherty in on-stage fight  Rock singer ...  entertainment
3  Snicket tops US box office chart  The film ada...  entertainment
4  Oceans Twelve raids box office  Oceans Twelve,...  entertainment

In [34]:
df.isnull().sum()

Article     0
Category    0
dtype: int64

In [35]:
df.dropna(inplace=True)

In [36]:
df['Article'] = df['Article'].str.lower()

In [38]:
df['Article'] = df['Article'].apply(
    lambda x: re.sub(r'[^a-zA-Z ]','',x)
)

In [39]:
stop_words = set(stopwords.words('english'))

df['Article'] = df['Article'].apply(
    lambda x: " ".join(
        word for word in x.split()
        if word not in stop_words
    )
)

In [40]:
X = df['Article']
y = df['Category']

In [41]:
tfidf = TfidfVectorizer(max_features=5000)
X = tfidf.fit_transform(X)

In [42]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [43]:
model = MultinomialNB()

model.fit(X_train, y_train)

MultinomialNB()

In [44]:
prediction = model.predict(X_test)

In [45]:
accuracy = accuracy_score(y_test, prediction)

print("Accuracy :", accuracy)

Accuracy : 0.9685393258426966

In [46]:
print(classification_report(y_test, prediction))

               precision    recall  f1-score   support

     business       0.95      0.98      0.97       103
entertainment       1.00      0.98      0.99        84
     politics       0.92      0.97      0.95        80
        sport       0.99      0.99      0.99        98
         tech       0.99      0.91      0.95        80

     accuracy                           0.97       445
    macro avg       0.97      0.97      0.97       445
 weighted avg       0.97      0.97      0.97       445